// Code generated by "stringer -type=CommandOp"; DO NOT EDIT

package state

import "fmt"

const _CommandOp_name = "AddServiceOpDelServiceOpAddDestinationOpDelDestinationOpAddCheckOpDelCheckOpUpdateCheckOp"

var _CommandOp_index = [...]uint8{0, 12, 24, 40, 56, 66, 76, 89}

func (i CommandOp) String() string {
	if i < 0 || i >= CommandOp(len(_CommandOp_index)-1) {
		return fmt.Sprintf("CommandOp(%d)", i)
	}
	return _CommandOp_name[_CommandOp_index[i]:_CommandOp_index[i+1]]
}
