package mocks

import mock "github.com/stretchr/testify/mock"
import state "github.com/luizbafilho/fusis/state"
import types "github.com/luizbafilho/fusis/types"

// State is an autogenerated mock type for the State type
type State struct {
	mock.Mock
}

// AddDestination provides a mock function with given fields: dst
func (_m *State) AddDestination(dst types.Destination) {
	_m.Called(dst)
}

// AddService provides a mock function with given fields: svc
func (_m *State) AddService(svc types.Service) {
	_m.Called(svc)
}

// Copy provides a mock function with given fields:
func (_m *State) Copy() state.State {
	ret := _m.Called()

	var r0 state.State
	if rf, ok := ret.Get(0).(func() state.State); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(state.State)
		}
	}

	return r0
}

// DeleteDestination provides a mock function with given fields: dst
func (_m *State) DeleteDestination(dst *types.Destination) {
	_m.Called(dst)
}

// DeleteService provides a mock function with given fields: svc
func (_m *State) DeleteService(svc *types.Service) {
	_m.Called(svc)
}

// GetDestination provides a mock function with given fields: name
func (_m *State) GetDestination(name string) (*types.Destination, error) {
	ret := _m.Called(name)

	var r0 *types.Destination
	if rf, ok := ret.Get(0).(func(string) *types.Destination); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Destination)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDestinations provides a mock function with given fields: svc
func (_m *State) GetDestinations(svc *types.Service) []types.Destination {
	ret := _m.Called(svc)

	var r0 []types.Destination
	if rf, ok := ret.Get(0).(func(*types.Service) []types.Destination); ok {
		r0 = rf(svc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Destination)
		}
	}

	return r0
}

// GetService provides a mock function with given fields: name
func (_m *State) GetService(name string) (*types.Service, error) {
	ret := _m.Called(name)

	var r0 *types.Service
	if rf, ok := ret.Get(0).(func(string) *types.Service); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Service)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServices provides a mock function with given fields:
func (_m *State) GetServices() []types.Service {
	ret := _m.Called()

	var r0 []types.Service
	if rf, ok := ret.Get(0).(func() []types.Service); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Service)
		}
	}

	return r0
}

// UpdateDestinations provides a mock function with given fields: dsts
func (_m *State) UpdateDestinations(dsts []types.Destination) {
	_m.Called(dsts)
}

// UpdateServices provides a mock function with given fields: svcs
func (_m *State) UpdateServices(svcs []types.Service) {
	_m.Called(svcs)
}

var _ state.State = (*State)(nil)
